name: "Easy Zip Files"
description: "Action for zipping files and folders easily"
inputs:
  files:
    description: "Files or directories to zip, glob patterns are supported"
    required: true
  dest:
    description: "Name of output zip file"
    required: false
    default: "result.zip"
  recursive:
    description: "Whether to add subdirectories to simply zip all files to the root"
    required: false
    default: false
branding:
  icon: "package"
  color: "red"
runs:
  using: "node16"
  main: "dist/index.js"
